server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true

logging.level:
  org.hibernate.SQL: debug


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    jwt:
      signKey: 123@#$$
